applications:
  backend:
    source:
      root: backend

    type: python:3.12

    relationships:
      database: "postgresql:15"

    dependencies:
      python3:
        gunicorn: '*'

    hooks:
      build: |
        pip install -r requirements.txt
      deploy: |
        alembic upgrade head

    web:
      commands:
        start: |
          gunicorn main:app --bind 0.0.0.0:$PORT

    variables:
      env:
        PYTHON_VERSION: "3.11"
        PYTHONPATH: "/app/backend"

routes:
  # "https://{default}":
  #   type: upstream
  #   upstream: "frontend:http"

  "https://api.{default}":
    type: upstream
    upstream: "backend:http"

services:
  postgres:
    type: postgresql:16
