applications:
  backend:
    source:
      root: backend

    type: python:3.12

    relationships:
      database:
        service: postgresql
        endpoint: postgresql

    dependencies:
      python3:
        gunicorn: '*'

    hooks:
      build: |
        pip install -r requirements.txt
      deploy: |
        alembic upgrade head

    web:
      commands:
        start: |
          fastapi run --host 0.0.0.0 --port $PORT main.py

    variables:
      env:
        PYTHON_VERSION: "3.11"
        PYTHONPATH: "/app/backend"

  frontend:
    source:
      root: frontend

    type: node:20

    mounts:
      "/.npm":
        source: "storage"
        source_path: "npm"
      "/.cache":
        source: "storage"
        source_path: "cache"

    hooks:
      build: |
        npm install
        npm run build

    web:
      commands:
        start: |
          npx next start -p $PORT

routes:
  # "https://{default}":
  #   type: upstream
  #   upstream: "frontend:http"

  "https://api.{default}":
    type: upstream
    upstream: "backend:http"

services:
  postgresql:
    type: postgresql:16
