"""add_slug_to_orders

Revision ID: 4045f1bf379c
Revises: df6c64613dd2
Create Date: 2024-03-19 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4045f1bf379c'
down_revision: Union[str, None] = 'df6c64613dd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('slug', sa.String(), nullable=True))
    op.create_index(op.f('ix_orders_slug'), 'orders', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_slug'), table_name='orders')
    op.drop_column('orders', 'slug')
    # ### end Alembic commands ###
